#!/bin/bash
if [ $# -lt 3 ]
then
    echo Usage:
    echo "  $0 COURSE-ID OUTPUT-DIRECTORY PROBLEM-NAME1 ..."
    echo
    echo Example:
    echo "  $0 13 20170909-test words_ending_with words_beginning_with primary_stress_position"
    exit 1
fi
if [ -z "$CLOUDCODER_ROOT" ]
then
    echo Environment variable CLOUDCODER_ROOT must be set!
    exit 1
fi    
src=$CLOUDCODER_ROOT/src
java -cp $src/EDSService/bin:$src/UACloudCoderCodeExtractionService/bin:$src/CloudCoderWebServer/cloudcoderApp.jar:$src/CloudCoderModelClassesPersistence/cloudcoderModelClassesPersist.jar:$src/CloudCoderModelClasses/cloudcoderModelClasses.jar:$src/deps/mysql-connector-java-5.1.16.jar edu.arizona.cs.practice.codeextraction.CodeExtractor $*
